name: DEMO_CI

on: 
  push: 
    branches: 
    - master
    # paths: 
    # - src/*
  pull_request: 
    branches: 
    - master

jobs: 
  jobname: 
    runs-on: ubuntu-latest
    
    steps: 

      - name: Checkout
        uses: actions/checkout@master

      - name: Run
        run: |
          echo hello
          echo world
