name: DEMO_CI

on: 
  push: 
    branches:
    - master
    paths: 
    - src/*

jobs: 
  jobname: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@master
      - name: Node
        uses: actions/steup-node@v1
      - name: Run
        run: |
          echo hello
          echo world
