name: DEMO_CI

on: 
  push: 
    branches:
    - master
    paths: 
    - src/*

jobs: 
  jobname: 
    runs-on: ubuntu-latest
    steps: 
    -name: checkout
      -uses: actions/checkout@v1
    -name: node
      -uses: actions/steup-node@v1
      -run: |
        echo hello
        echo world
